### ISSUE TITLE
Discontinue support for single-wire geometry

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icarusalg#31]
By now, single-wire first induction plane geometry is an historical curiosity.
Geometry has evolved a lot from there, and I think it's time to retire this old take of it.

**Comment by wesketchum** [comment]
@PetrilloAtWork @SFBayLaser this is resolved?

**Comment by PetrilloAtWork** [comment]
It's not.

**Comment by SFBayLaser** [comment]
Isn't this in effect done already? I am not aware that we are "supporting" single wire anymore. Or do you mean we should eliminate all historical references to it (e.g. in fhicl files)?

**Comment by PetrilloAtWork** [comment]
Yes, I mean to eliminate the configuration for that geometry and the GDML files, so that they don't become a maintenance hurdle.
